#!/bin/sh
set -e
systemctl disable check-ping-shutdown || true
rm -f /usr/bin/check-ping-shutdown.sh
rm -f /etc/systemd/system/check-ping-shutdown.service
rm -f /etc/check-ping-shutdown.conf
echo "check-ping-shutdown service removed."
