#!/bin/sh
set -e

# Configuration file
CONFIG="/etc/systemd/system/check-ping-shutdown.conf"

# Only create config if it doesn't exist
if [ ! -f "$CONFIG" ]; then
    cat > "$CONFIG" << 'EOL'
# If PING_SERVER is down or unreachable, this will shutdown your appliance.
# It's better to use IP rather than hostname incase there is a DNS issue.
# e.g. PING_SERVER=192.168.1.5
PING_SERVER=

# TIMEOUT (in seconds) is the amount of time  will start counting down once PING_SERVER goes offline.
# i.e. how long do you anticipate your longest brownout to be. Don't set too high or your UPS might not have the juice for it.
TIMEOUT=60

# Two options for DRY:
# TRUE   - This will run the script/service in dry mode where shutdown commands are only logged.
# FALSE  - The service will actually shutdown this host. Set as default to inspect behaviour before usage.
DRY=TRUE

# There are two options for MODE:
# ACTIVE - As long as PING_SERVER comes back up before the timeout is reached the host will not shut itself down.
# ALWAYS - Will always shutdown your host after the timeout is reached. It doesn't care if PING_SERVER comes back up.
MODE=ACTIVE
EOL
fi

systemctl daemon-reload
systemctl enable check-ping-shutdown
echo "check-ping-shutdown service installed."
