name: Docker Image CI

on:
  push:
    paths:
      - '*Dockerfile*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./server --tag check-ping-shutdown:$(date +%s)
